name: CI/CD - Dev
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      # - name: Set Environment File
      #   run: cp .env.dev .env

      - name: Lint & Test
        run: |
          npm run lint
          npm test

      # # Build APK (Android)
      # - name: Build APK
      #   run: |
      #     cd android
      #     ./gradlew assembleRelease
      #   env:
      #     ENVFILE: .env.dev

      # # Build IPA (iOS)
      # - name: Build IPA
      #   if: runner.os == 'macOS'
      #   run: |
      #     cd ios
      #     xcodebuild -workspace YourApp.xcworkspace \
      #       -scheme YourApp \
      #       -sdk iphoneos \
      #       -configuration Release \
      #       archive -archivePath $PWD/build/YourApp.xcarchive
      #   env:
      #     ENVFILE: .env.dev

      # # Deploy to Dev
      # - name: Deploy to Dev
      #   run: echo "Deploying to Dev Environment"
