name: CI/CD - Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      # - name: Set Environment File
      #   run: cp .env.prod .env

      - name: Lint & Test
        run: |
          npm run lint
          npm test

    