name: CI/CD - Test

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      # - name: Set Environment File
      #   run: cp .env.test .env

      # - name: Lint & Test
      #   run: |
      #     npm run lint
      #     npm test

      # # Build APK (Android)
      # - name: Build APK
      #   run: |
      #     cd android
      #     ./gradlew assembleRelease
      #   env:
      #     ENVFILE: .env.test

      # # Build IPA (iOS)
      # - name: Build IPA
      #   if: runner.os == 'macOS'
      #   run: |
      #     cd ios
      #     xcodebuild -workspace YourApp.xcworkspace \
      #       -scheme YourApp \
      #       -sdk iphoneos \
      #       -configuration Release \
      #       archive -archivePath $PWD/build/YourApp.xcarchive
      #   env:
      #     ENVFILE: .env.test

      # # Deploy to Test
      # - name: Deploy to Test
      #   run: echo "Deploying to Test Environment"
